
document.writeln("<div id=\"juz1\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-1  <a href=\"#j30\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz30\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz1\')\"><a style=\"color: #fff;\" href=\"#j1\" onClick=\"return noHistory(this);\">Al-Fatihah-1~Al-Baqarah-141</button></a> <a href=\"#j2\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz2\')\"></button></a></div><div class=\"overflo\">   <div id=\'j1\'></div><script src=\"alquran/01b.js\"></script> <script src=\"alquran/02-1-141.js\"></script></div></div>");

document.writeln("<div id=\"juz2\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-2  <a href=\"#j1\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz1\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz2\')\"><a style=\"color: #fff;\" href=\"#j2\" onClick=\"return noHistory(this);\">Al-Baqarah-142~Al-Baqarah-251</button></a> <a href=\"#j3\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz3\')\"></button></a></div><div class=\"overflo\">  <div id=\'j2\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/02-142-251.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz3\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-3  <a href=\"#j2\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz2\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz3\')\"><a style=\"color: #fff;\" href=\"#j3\" onClick=\"return noHistory(this);\">Al-Baqarah-252~Al-'Imraan-91</button></a> <a href=\"#j4\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz4\')\"></button></a></div><div class=\"overflo\">  <div id=\'j3\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/02-252-286.js\"></script><script src=\"alquran/03-1-91.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz4\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-4  <a href=\"#j3\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz3\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz4\')\"><a style=\"color: #fff;\" href=\"#j4\" onClick=\"return noHistory(this);\">Al-'Imraan-92~An-Nisaa'-23</button></a> <a href=\"#j5\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz5\')\"></button></a></div><div class=\"overflo\">  <div id=\'j4\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/03-92-200.js\"></script><script src=\"alquran/04-1-23.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz5\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-5  <a href=\"#j4\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz4\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz5\')\"><a style=\"color: #fff;\" href=\"#j5\" onClick=\"return noHistory(this);\">An-Nisaa'-24~An-Nisaa'-147</button></a> <a href=\"#j6\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz6\')\"></button></a></div><div class=\"overflo\">  <div id=\'j5\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/04-24-147.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz6\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-6  <a href=\"#j5\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz5\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz6\')\"><a style=\"color: #fff;\" href=\"#j6\" onClick=\"return noHistory(this);\">An-Nisaa'-148~Al-Maa'idah-82</button></a> <a href=\"#j7\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz7\')\"></button></a></div><div class=\"overflo\">  <div id=\'j6\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/04-148-176.js\"></script> <script src=\"alquran/05-1-82.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz7\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-7  <a href=\"#j6\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz6\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz7\')\"><a style=\"color: #fff;\" href=\"#j7\" onClick=\"return noHistory(this);\">Al-Maa'dah-83~Al-An'aam-110</button></a> <a href=\"#j8\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz8\')\"></button></a></div><div class=\"overflo\">  <div id=\'j7\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/05-83-120.js\"></script> <script src=\"alquran/06-1-110.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz8\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-8  <a href=\"#j7\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz7\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz8\')\"><a style=\"color: #fff;\" href=\"#j8\" onClick=\"return noHistory(this);\">Al-An'aam-111~Al-'Araaf-87</button></a> <a href=\"#j9\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz9\')\"></button></a></div><div class=\"overflo\"> <div id=\'j8\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/06-111-165.js\"></script> <script src=\"alquran/07-1-87.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz9\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-9  <a href=\"#j8\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz8\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz9\')\"><a style=\"color: #fff;\" href=\"#j9\" onClick=\"return noHistory(this);\">Al-'Araaf-88~Al-Anfaal-40</button></a> <a href=\"#j10\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz10\')\"></button></a></div><div class=\"overflo\"> <div id=\'j9\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/07-88-206.js\"></script> <script src=\"alquran/08-1-40.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz10\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-10  <a href=\"#j9\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz9\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz10\')\"><a style=\"color: #fff;\" href=\"#j10\" onClick=\"return noHistory(this);\">Al-Anfaal-41~At-Taubah-93</button></a> <a href=\"#j11\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz11\')\"></button></a></div><div class=\"overflo\"> <div id=\'j10\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/08-41-75.js\"></script> <script src=\"alquran/09-1-93.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz11\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-11  <a href=\"#j10\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz10\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz11\')\"><a style=\"color: #fff;\" href=\"#j11\" onClick=\"return noHistory(this);\">At-Taubah-94~Huud-5</button></a> <a href=\"#j12\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz12\')\"></button></a></div><div class=\"overflo\"> <div id=\'j11\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/09-94-129.js\"></script> <script src=\"alquran/10-1-109.js\"></script><script src=\"alquran/11-1-5.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz12\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-12  <a href=\"#j11\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz11\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz12\')\"><a style=\"color: #fff;\" href=\"#j12\" onClick=\"return noHistory(this);\">Huud-6~Yusuf-52</button></a> <a href=\"#j13\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz13\')\"></button></a></div><div class=\"overflo\"> <div id=\'j12\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/11-6-123.js\"></script> <script src=\"alquran/12-1-52.js\"></script> <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz13\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-13  <a href=\"#j12\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz12\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz13\')\"><a style=\"color: #fff;\" href=\"#j13\" onClick=\"return noHistory(this);\">Yusuf-53~Al-Hijr-1</button></a> <a href=\"#j14\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz14\')\"></button></a></div><div class=\"overflo\"> <div id=\'j13\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/12-53-111.js\"></script> <script src=\"alquran/13-1-43.js\"></script> <script src=\"alquran/14-1-52.js\"></script><script src=\"alquran/15-1.js\"></script> <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz14\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-14  <a href=\"#j13\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz13\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz14\')\"><a style=\"color: #fff;\" href=\"#j14\" onClick=\"return noHistory(this);\">Al-Hijr-2~An-Nahl-128</button></a> <a href=\"#j15\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz15\')\"></button></a></div><div class=\"overflo\"> <div id=\'j14\'></div>  <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/15-2-99.js\"></script> <script src=\"alquran/16-1-128.js\"></script> <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz15\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-15  <a href=\"#j14\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz14\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz15\')\"><a style=\"color: #fff;\" href=\"#j15\" onClick=\"return noHistory(this);\">Al-Israa'-1~Al-Kahfi-74</button></a> <a href=\"#j16\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz16\')\"></button></a></div><div class=\"overflo\"> <div id=\'j15\'></div>  <script src=\"alquran/17-1-111.js\"></script> <script src=\"alquran/18-1-74.js\"></script> <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz16\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-16  <a href=\"#j15\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz15\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz16\')\"><a style=\"color: #fff;\" href=\"#j16\" onClick=\"return noHistory(this);\">Al-Kahfi-75~Ath-Thahaa-135</button></a> <a href=\"#j17\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz17\')\"></button></a></div><div class=\"overflo\">  <div id=\'j16\'></div>  <script src=\"alquran/basmalahjus.js\"></script>  <script src=\"alquran/18-75-110.js\"></script> <script src=\"alquran/19.js\"></script>  <script src=\"alquran/20.js\"></script> <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz17\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-17  <a href=\"#j16\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz16\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz17\')\"><a style=\"color: #fff;\" href=\"#j17\" onClick=\"return noHistory(this);\">Al-Anbiyaa'-1~Al-Hajj-78</button></a> <a href=\"#j18\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz18\')\"></button></a></div><div class=\"overflo\">  <div id=\'j17\'></div> <script src=\"alquran/21.js\"></script> <script src=\"alquran/22.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz18\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-18  <a href=\"#j17\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz17\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz18\')\"><a style=\"color: #fff;\" href=\"#j18\" onClick=\"return noHistory(this);\">Al-Mu'minuun-1~Al-Furqaan-20</button></a> <a href=\"#j19\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz19\')\"></button></a></div><div class=\"overflo\">  <div id=\'j18\'></div> <script src=\"alquran/23.js\"></script> <script src=\"alquran/24.js\"></script> <script src=\"alquran/25-1-20.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz19\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-19  <a href=\"#j18\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz18\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz19\')\"><a style=\"color: #fff;\" href=\"#j19\" onClick=\"return noHistory(this);\">Al-Furqaan-21~An-Naml-59</button></a> <a href=\"#j20\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz20\')\"></button></a></div><div class=\"overflo\">  <div id=\'j19\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/25-21-77.js\"></script> <script src=\"alquran/26.js\"></script><script src=\"alquran/27-1-59.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz20\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-20  <a href=\"#j19\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz19\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz20\')\"><a style=\"color: #fff;\" href=\"#j20\" onClick=\"return noHistory(this);\">An-Naml-60~Al-'Ankabuut-44</button></a> <a href=\"#j21\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz21\')\"></button></a></div><div class=\"overflo\">  <div id=\'j20\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/27-60-93.js\"></script> <script src=\"alquran/28.js\"></script><script src=\"alquran/29-1-44.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz21\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-21  <a href=\"#j20\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz20\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz21\')\"><a style=\"color: #fff;\" href=\"#j21\" onClick=\"return noHistory(this);\">Al-'Ankabuut-45~Al-Ahzab-30</button></a> <a href=\"#j22\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz22\')\"></button></a></div><div class=\"overflo\">  <div id=\'j21\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/29-45-69.js\"></script> <script src=\"alquran/30.js\"></script> <script src=\"alquran/31.js\"></script> <script src=\"alquran/32.js\"></script><script src=\"alquran/33-1-30.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz22\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-22  <a href=\"#j21\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz21\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz22\')\"><a style=\"color: #fff;\" href=\"#j22\" onClick=\"return noHistory(this);\">Al-Ahzab-31~Yaasiin-21</button></a> <a href=\"#j23\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz23\')\"></button></a></div><div class=\"overflo\">  <div id=\'j22\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/33-31-73.js\"></script> <script src=\"alquran/34.js\"></script> <script src=\"alquran/35.js\"></script><script src=\"alquran/36-1-21.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz23\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-23  <a href=\"#j22\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz22\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz23\')\"><a style=\"color: #fff;\" href=\"#j23\" onClick=\"return noHistory(this);\">Yaasiin-22~Az-Zumar-31</button></a> <a href=\"#j24\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz24\')\"></button></a></div><div class=\"overflo\">  <div id=\'j23\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/36-22-83.js\"></script> <script src=\"alquran/37.js\"></script> <script src=\"alquran/38.js\"></script><script src=\"alquran/39-1-31.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz24\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-24  <a href=\"#j23\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz23\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz24\')\"><a style=\"color: #fff;\" href=\"#j24\" onClick=\"return noHistory(this);\">Az-Zumar-32~Fushshilat-46</button></a> <a href=\"#j25\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz25\')\"></button></a></div><div class=\"overflo\">  <div id=\'j24\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/39-32-75.js\"></script> <script src=\"alquran/40.js\"></script> <script src=\"alquran/41-1-46.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz25\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-25  <a href=\"#j24\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz24\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz25\')\"><a style=\"color: #fff;\" href=\"#j25\" onClick=\"return noHistory(this);\">Fushshilat-47~Al-Jatsiyah-37</button></a> <a href=\"#j26\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz26\')\"></button></a></div><div class=\"overflo\">  <div id=\'j25\'></div> <script src=\"alquran/basmalahjus.js\"></script> <script src=\"alquran/41-47-54.js\"></script> <script src=\"alquran/42.js\"></script> <script src=\"alquran/43.js\"></script> <script src=\"alquran/44.js\"></script>  <script src=\"alquran/45.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz26\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-26  <a href=\"#j25\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz25\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz26\')\"><a style=\"color: #fff;\" href=\"#j26\" onClick=\"return noHistory(this);\">Al-Ahqaaf-1~Adz-Dzariyaat-30</button></a> <a href=\"#j27\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz27\')\"></button></a></div><div class=\"overflo\">  <div id=\'j26\'></div>  <script src=\"alquran/46.js\"></script> <script src=\"alquran/47.js\"></script> <script src=\"alquran/48.js\"></script> <script src=\"alquran/49.js\"></script>  <script src=\"alquran/50.js\"></script>  <script src=\"alquran/51-1-30.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz27\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-27  <a href=\"#j26\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz26\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz27\')\"><a style=\"color: #fff;\" href=\"#j27\" onClick=\"return noHistory(this);\">Adz-Dzariyaat-31~Al-Hadiid-29</button></a> <a href=\"#j28\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz28\')\"></button></a></div><div class=\"overflo\">  <div id=\'j27\'></div>  <script src=\"alquran/basmalahjus.js\"></script>   <script src=\"alquran/51-31-60.js\"></script> <script src=\"alquran/52.js\"></script> <script src=\"alquran/53.js\"></script> <script src=\"alquran/54.js\"></script>  <script src=\"alquran/55.js\"></script>  <script src=\"alquran/56.js\"></script>  <script src=\"alquran/57.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz28\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-28  <a href=\"#j27\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz27\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz28\')\"><a style=\"color: #fff;\" href=\"#j28\" onClick=\"return noHistory(this);\">Al-Mujaadilah-1~At-Tahriim-12</button></a> <a href=\"#j29\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz29\')\"></button></a></div><div class=\"overflo\">  <div id=\'j28\'></div>  <script src=\"alquran/58.js\"></script> <script src=\"alquran/59.js\"></script> <script src=\"alquran/60.js\"></script> <script src=\"alquran/61.js\"></script>  <script src=\"alquran/62.js\"></script>  <script src=\"alquran/63.js\"></script>  <script src=\"alquran/64.js\"></script>  <script src=\"alquran/65.js\"></script>  <script src=\"alquran/66.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz29\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-29  <a href=\"#j28\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz28\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz29\')\"><a style=\"color: #fff;\" href=\"#j29\" onClick=\"return noHistory(this);\">Al-Mulk-1~Al-Mursalat-50</button></a> <a href=\"#j30\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz30\')\"></button></a></div><div class=\"overflo\">  <div id=\'j29\'></div>  <script src=\"alquran/67.js\"></script> <script src=\"alquran/68.js\"></script> <script src=\"alquran/69.js\"></script> <script src=\"alquran/70.js\"></script>  <script src=\"alquran/71.js\"></script>  <script src=\"alquran/72.js\"></script>  <script src=\"alquran/73.js\"></script>  <script src=\"alquran/74.js\"></script>  <script src=\"alquran/75.js\"></script>  <script src=\"alquran/76.js\"></script>  <script src=\"alquran/77.js\"></script>  <script src=\"alquran/end.js\"></script></div></div>");

document.writeln("<div id=\"juz30\" class=\"tabcontent\"><div class=\"headerjuz\">Juz-30  <a href=\"#j29\" onClick=\"return noHistory(this);\"><button class=\"nex\" onclick=\"openCity(event, \'juz29\')\"></button></a>  <button class=\"glow-on-hover\" onclick=\"openCity(event, \'juz30\')\"><a style=\"color: #fff;\" href=\"#j30\" onClick=\"return noHistory(this);\">An-Nabaa'-1~An-Naas-6</button></a> <a href=\"#j1\" onClick=\"return noHistory(this);\"><button class=\"pre\" onclick=\"openCity(event, \'juz1\')\"></button></a></div><div class=\"overflo\">  <div id=\'j30\'></div>  <script src=\"alquran/78.js\"></script> <script src=\"alquran/79.js\"></script> <script src=\"alquran/80.js\"></script> <script src=\"alquran/81.js\"></script> <script src=\"alquran/82.js\"></script>  <script src=\"alquran/83.js\"></script>  <script src=\"alquran/84.js\"></script>  <script src=\"alquran/85.js\"></script>  <script src=\"alquran/86.js\"></script>  <script src=\"alquran/87.js\"></script> <script src=\"alquran/88.js\"></script><script src=\"alquran/89.js\"></script><script src=\"alquran/90.js\"></script><script src=\"alquran/91.js\"></script><script src=\"alquran/92.js\"></script><script src=\"alquran/93.js\"></script><script src=\"alquran/94.js\"></script><script src=\"alquran/95.js\"></script><script src=\"alquran/96.js\"></script><script src=\"alquran/97.js\"></script><script src=\"alquran/98.js\"></script><script src=\"alquran/99.js\"></script><script src=\"alquran/100.js\"></script><script src=\"alquran/101.js\"></script><script src=\"alquran/102.js\"></script><script src=\"alquran/103.js\"></script><script src=\"alquran/104.js\"></script><script src=\"alquran/105.js\"></script><script src=\"alquran/106.js\"></script><script src=\"alquran/107.js\"></script><script src=\"alquran/108.js\"></script><script src=\"alquran/109.js\"></script><script src=\"alquran/110.js\"></script><script src=\"alquran/111.js\"></script><script src=\"alquran/112.js\"></script><script src=\"alquran/113.js\"></script><script src=\"alquran/114.js\"></script><script src=\"alquran/end.js\"></script></div></div>");

